[project]
multi_person = false
frame_rate = 60
frame_range = []
exclude_from_batch = []

[pose]
pose_framework = "openpose"
pose_model = "BODY_135"
overwrite_pose = false
openpose_path = ""

[synchronization]
display_sync_plots = true
keypoints_to_consider = "all"
approx_time_maxspeed = "auto"
reset_sync = false

[calibration]
calibration_type = "calculate"

[personAssociation]
likelihood_threshold_association = 0.3

[triangulation]
reorder_trc = false
reproj_error_threshold_triangulation = 15
likelihood_threshold_triangulation = 0.3
min_cameras_for_triangulation = 2
interpolation = "cubic"
interp_if_gap_smaller_than = 10
show_interp_indices = true
handle_LR_swap = false
undistort_points = false
make_c3d = false

[filtering]
type = "butterworth"
display_figures = false
make_c3d = false

[markerAugmentation]
participant_height = "1.63"
participant_mass = "62.9"
make_c3d = false

[opensim]
static_trial = [ "S00_P00_Participant/S00_P00_T00_StaticTrial",]
opensim_bin_path = "C:\\Users\\kadava\\Documents\\GitHub\\demo_3Dtracking_pose2sim_updated\\Pose2Sim"

[pose.CUSTOM]
name = "CHip"
id = "None"
[[pose.CUSTOM.children]]
name = "RHip"
id = 12
[[pose.CUSTOM.children.children]]
name = "RKnee"
id = 14
[[pose.CUSTOM.children.children.children]]
name = "RAnkle"
id = 16
[[pose.CUSTOM.children.children.children.children]]
name = "RBigToe"
id = 22
[[pose.CUSTOM.children.children.children.children.children]]
name = "RSmallToe"
id = 23


[[pose.CUSTOM.children.children.children.children]]
name = "RHeel"
id = 24




[[pose.CUSTOM.children]]
name = "LHip"
id = 11
[[pose.CUSTOM.children.children]]
name = "LKnee"
id = 13
[[pose.CUSTOM.children.children.children]]
name = "LAnkle"
id = 15
[[pose.CUSTOM.children.children.children.children]]
name = "LBigToe"
id = 19
[[pose.CUSTOM.children.children.children.children.children]]
name = "LSmallToe"
id = 20


[[pose.CUSTOM.children.children.children.children]]
name = "LHeel"
id = 21




[[pose.CUSTOM.children]]
name = "Neck"
id = 17
[[pose.CUSTOM.children.children]]
name = "Head"
id = 18
[[pose.CUSTOM.children.children.children]]
name = "Nose"
id = 0


[[pose.CUSTOM.children.children]]
name = "RShoulder"
id = 6
[[pose.CUSTOM.children.children.children]]
name = "RElbow"
id = 8
[[pose.CUSTOM.children.children.children.children]]
name = "RWrist"
id = 10



[[pose.CUSTOM.children.children]]
name = "LShoulder"
id = 5
[[pose.CUSTOM.children.children.children]]
name = "LElbow"
id = 7
[[pose.CUSTOM.children.children.children.children]]
name = "LWrist"
id = 9




[calibration.convert]
convert_from = "qualisys"

[personAssociation.single_person]
reproj_error_threshold_association = 20
tracked_keypoint = "Neck"

[personAssociation.multi_person]
reconstruction_error_threshold = 0.1
min_affinity = 0.2

[filtering.butterworth]
order = 4
cut_off_frequency = 10

[filtering.kalman]
trust_ratio = 100
smooth = true

[filtering.butterworth_on_speed]
order = 4
cut_off_frequency = 10

[filtering.gaussian]
sigma_kernel = 2

[filtering.LOESS]
nb_values_used = 30

[filtering.median]
kernel_size = 9

[calibration.convert.qualisys]
binning_factor = 1

[calibration.convert.optitrack]

[calibration.convert.vicon]

[calibration.convert.opencap]

[calibration.convert.easymocap]

[calibration.convert.biocv]

[calibration.convert.anipose]

[calibration.convert.freemocap]

[calibration.calculate.intrinsics]
overwrite_intrinsics = false
show_detection_intrinsics = false
intrinsics_extension = "png"
extract_every_N_sec = 5
intrinsics_corners_nb = [ 8, 6,]
intrinsics_square_size = 86

[calibration.calculate.extrinsics]
calculate_extrinsics = true
extrinsics_method = "board"
moving_cameras = false

[calibration.calculate.extrinsics.board]
show_reprojection_error = true
extrinsics_extension = "png"
extrinsics_corners_nb = [ 8, 6,]
extrinsics_square_size = 86

[calibration.calculate.extrinsics.scene]
show_reprojection_error = true
extrinsics_extension = "png"
object_coords_3d = [ [ -2.0, 0.3, 0.0,], [ -2.0, 0.0, 0.0,], [ -2.0, 0.0, 0.05,], [ -2.0, -0.3, 0.0,], [ 0.0, 0.3, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.05,], [ 0.0, -0.3, 0.0,],]

[calibration.calculate.extrinsics.keypoints]
